CREATE TABLE IF NOT EXISTS metrics (
    "id" VARCHAR(250) PRIMARY KEY,
	"type" VARCHAR(50) NOT NULL,
	"delta" BIGINT NULL,
	"value" DOUBLE PRECISION NULL,
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);