name: Lint

on:
  push:
    branches: [ main ]
    tags-ignore: ['*']
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.1

    - name: Install dependencies
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        go install github.com/segmentio/golines@latest

    - name: Lint code
      run: |
        unformatted=$(go fmt ./...)
        if [ -n "$unformatted" ]; then 
          echo "These files are not formatted with 'go fmt': $unformatted"
          exit 1
        fi
        unformatted=$(find . -name '*.go' -exec goimports -local go-echo-ddd-template/ -l {} +)
        if [ -n "$unformatted" ]; then
          echo "These files are not formatted with 'goimports': $unformatted"
          exit 1
        fi
        unformatted=$(find . -name '*.go' -exec golines -w {} -m 120 \;)
        if [ -n "$unformatted" ]; then
          echo "These files are not formatted with 'golines': $unformatted"
          exit 1
        fi
        golangci-lint run ./...
